### ISSUE TITLE
How do I use it

### ISSUE THREAD

**Issue by loneyao** [somlor/kanban#33]

**Comment by cobbzilla** [comment]
@lengyao88 it might help to provide some more information about what you have tried, what hasn't worked for you, and what kinds of error messages you have received.

**Comment by CrashLaker** [comment]
How can I run this?

```
$ rake
rake aborted!
cannot load such file -- bundler/setup
/home/pactual.net/tomigaca/github/kanban/config/boot.rb:3:in `<top (required)>'
/home/pactual.net/tomigaca/github/kanban/config/application.rb:1:in `<top (required)>'
/home/pactual.net/tomigaca/github/kanban/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by CrashLaker** [comment]
$ ruby --version
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
```
$ gem install bundle -v 1
$ bundle install
$ rake
/usr/local/share/gems/gems/bundler-1.0.0/lib/bundler/shared_helpers.rb:3:in `<top (required)>': undefined method `source_index' for Gem:Module (NoMethodError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/gems/gems/bundler-1.0.0/lib/bundler/setup.rb:1:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:144:in `require'
        from /root/kanban/config/boot.rb:3:in `<top (required)>'
        from /root/kanban/bin/rake:2:in `require_relative'
        from /root/kanban/bin/rake:2:in `<main>'

```

**Comment by CrashLaker** [comment]
Was able to run till the command rake succeeded.. but now what..
some notes..
```
# install rvm
rvm install "ruby-2.2.2"
gem install bundler -v 1.10.4
bundle install
yum -y install postgresql-devel-9.2.24
gem install pg -v '0.18.3'
bundle install
rake
```
```
$ rake
...
...
Top 5 slowest example groups:
  Board
    0.29659 seconds average (0.59317 seconds / 2 examples) ./spec/models/board_spec.rb:19
  Api::BoardsController
    0.09267 seconds average (0.92668 seconds / 10 examples) ./spec/controllers/api/board_controller_spec.rb:4
  Card
    0.02719 seconds average (0.08158 seconds / 3 examples) ./spec/models/card_spec.rb:23
  User
    0.02483 seconds average (0.14897 seconds / 6 examples) ./spec/models/user_spec.rb:22
  List
    0.01541 seconds average (0.04624 seconds / 3 examples) ./spec/models/list_spec.rb:20

Finished in 1.94 seconds (files took 8.21 seconds to load)
24 examples, 0 failures, 2 pending

Randomized with seed 51671
```

**Comment by CrashLaker** [comment]
also
```
yum -y install postgresql-server postgresql-contrib
# setup proper username passwrd in config/database.yml
postgresql-setup initdb
systemctl start postgresql

su - postgres
createuser --interactive --pwprompt # create root role
createdb -O root kanban_production
createdb -O root kanban_test
createdb -O root kanban_development
```

then...
`rails s -b 0.0.0.0`

**Comment by CrashLaker** [comment]
how can i login now..

![image](https://user-images.githubusercontent.com/4432491/62753140-9e6b0d80-ba40-11e9-9ee7-b8f160434df2.png)


```
Started GET "/api/users/current" for 192.168.31.183 at 2019-08-08 23:56:32 -0400
Cannot render console from 192.168.31.183! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Api::UsersController#current as JSON
Filter chain halted as :require_login rendered or redirected
Completed 401 Unauthorized in 1ms (Views: 0.3ms | ActiveRecord: 0.0ms)
```

**Comment by CrashLaker** [comment]
cannot believe i actually had to..
```
gem install bcrypt
run file |
require 'bcrypt'

my_pwd = BCrypt::Password.create("your_password")
puts my_pwd
```
then insert into postgre
```
insert into users (email,password_digest) values ('root', 'pwd')
```
